booktype/Booktype

- scripts/createbooktype
These changes allow for Apache 2.4 systems not running mod_access_compat, improve security by denying directory indexes for static/ and data/ directories, and allow the setting of a ServerAdmin email address for users to contact in case of server errors.
> BK-1255 Improved Apache configuration template

- lib/booktype/apps/edit/tasks.py
- lib/booktype/convert/epub/constants.py
- lib/booktype/convert/epub/converter.py
- lib/booktype/convert/epub/cover.py
- lib/booktype/convert/epub/displayoptions.py
- lib/booktype/convert/epub/styles/style-rtl.css
- lib/booktype/convert/epub/writer.py
- lib/booktype/convert/epub/writerplugin.py
There is one problem with this. Epub Checker throws some reference errors on NCX file. 
nav.xhtml has paths to chapters that are in the same folder ( Text/ ) but the problem is that toc.ncx file generation use the same items that nav generation, but... toc.ncx is outside of Text/ folder so the reference links that it has are wrong. Those links need to be fixed to be something like Text/chapter.html instead of only chapter.html.
I tried many different way but at the end both toc.ncx and nav.xhtml are generated in write function of EpubWriter. We need to patch ebooklib to be able to have optional basepath for toc.ncx generation.
talk later
> BK-1371 Convert scripts for EPUB production

- lib/booktype/apps/edit/channel.py
BK-1415 Fast chapter hold/unhold bug.
Prevent creation of redundant toc objects during 'chapter_unhold' operation
> BK-1415 Fast chapter hold/unhold bug.

- lib/booktype/apps/edit/static/edit/js/booktype/toc.js
Discussed it with Julian, for now all chapters after unhold are displaying in the end of toc in root. This is server logic and it works.
After unhold we should display all chapters in the end of toc root.
> BK-1487 Chapters unhold into deleted section.

- lib/booktype/skeleton/themes/simple/editor.css
- lib/booktype/skeleton/themes/simple2/editor.css
This change makes less whitespace between two adjacent heading elements, as requested by Julian in https://dev.sourcefabric.org/browse/BK-1488
> BK-1488 Reduce top margin on heading elements

- lib/booktype/apps/edit/tasks.py
I've changed format to: "bookname-2015-08-17-12-25-14.pdf" due to sign ":" is reserved sign for some operation systems, including ms windows.
> BK-1621 Exported filenames could contain timestamp

- lib/booktype/apps/edit/static/edit/js/aloha/plugins/booktype/bookundo/lib/bookundo-plugin.js
Regarding redo issue which was mentioned in amnesty bug report. Redo function was implemented.
To use redo we should open edit menu and click redo, or use hot keys "cmnd + shift + z" for mac and "ctrl + shift + z" for windows/linux.
> BK-1674 Strange behavior in undo plugin in case of fast typing with enabled tracking

- lib/booktype/apps/edit/__init__.py
- lib/booktype/locale/en/LC_MESSAGES/django.po
Just so this checkbox matches the button label in the editor. 'Approve' is not the exact opposite of 'Decline'.
> BK-1681 Consistent use of 'Accept changes'

- lib/booktype/apps/edit/static/edit/css/slider.css
- lib/booktype/apps/themes/templates/themes/panel.html
- lib/booktype/skeleton/themes/custom/panel.html
Tooltips on these sliders have a precision bug, and we don't need the tooltips because the value of the slider is shown immediately to the right anyhow. Least intrusive solution is just to hide these particular tooltips. Also put the left margin back in place for the sliders, so that the full handle can be seen when the value is at minimum. 
Other enhancements are to allow 5% precision for sliders instead of 10%, and set a default for custom style line height of 130% instead of 100%.
> BK-1682 Hide redundant slider tooltips, fix left margin for sliders

- lib/booktype/skeleton/base_settings.py.original
So it turns out the reason British localization wasn't working was that I used the underscore form of the language code, when I should have used the hyphenated form.
Also we have a bunch of new languages from Transifex to add.
> BK-1659 Fix language code for Great Britain, add other new languages

- lib/booktypecontrol/templates/booktypecontrol/control_center_settings.html
This page doesn't do anything now. In the short term, just hide it from instance admins.
> BK-1673 Hide Publishing Defaults page from the Control Centre

- lib/booktype/convert/mpdf/converter.py
This fix works for URLs in sentences where punctuation follows the link, and also where a normal space follows the link.
> BK-1788 Remove trailing space after bracket

- lib/booktype/apps/account/templates/account/form_signin.html
- lib/booktype/apps/account/templates/account/register.html
- lib/booktype/locale/en/LC_MESSAGES/django.po
To avoid duplicate translations, we can use the same string throughout and apply a text-transform where required.
> BK-1804 Fix remaining inconsistencies with 'sign in'

- lib/booktype/skeleton/base_settings.py.original
Just because the other labels are shown in the native language.
> BK-1837 Translate Norwegian label in interface language menu

- lib/booktype/apps/edit/templates/edit/book_edit.html
- lib/booktype/locale/en/LC_MESSAGES/django.po
Although the editor sidebar control has the same label as the book-level setting, it has a different effect.
> BTPRO-804 Clarify that the Track Changes control is not persistent

- lib/booktype/apps/edit/templates/edit/panel_settings.html
This check should hide the menu heading if users can't see either of the following Security menu items.
> BK-1852 Hide heading if users don't have permission to see Security menu

- .gitignore
- lib/booktype/apps/export/utils.py
- lib/booktype/constants.py
- lib/booktype/utils/misc.py
- lib/booktype/utils/security/__init__.py
- lib/booktype/utils/security/base.py
- lib/booktype/utils/tests/test_security.py
This PRs allow us to extends the Security module in custom instances, doing something like this:
```python
BOOKTYPE_BASE_SECURITY_CLASS = 'my_book_site.custom.module.Security'
```
```python
from booktype.utils.security.base import BaseSecurity
class MySecurity(BaseSecurity):
""" own security class """
def _get_default_role(self, book=None):
if user.is_something:
return CustomDefaultRole() # with custom permissions
return super(MySecurity, self)._get_default_role(book)
```
then BookSecurity and GroupSecurity will inherit this class and this will be the standard Security object used inside Booktype
> BK-1862 Make Security module more extendable

- lib/booktype/apps/portal/templates/portal/group.html
- lib/booktype/apps/portal/templates/portal/group_remove_book.html
- lib/booktype/apps/portal/urls.py
- lib/booktype/apps/portal/views.py
The user who is not authorized to remove the book from group (is not superuser or group admin or book owner and group member) will not see "remove" button for a book in current group view
Also confirmation modal pops up.
Will need to create a couple of new strings for translations
> BK-1861 Functionality to remove book from group

- lib/booktype/apps/themes/templates/themes/academic/body_mpdf.html
- lib/booktype/apps/themes/templates/themes/academic/body_screenpdf.html
- lib/booktype/apps/themes/templates/themes/academic/endmatter_mpdf.html
- lib/booktype/apps/themes/templates/themes/academic/endmatter_screenpdf.html
- lib/booktype/apps/themes/templates/themes/academic/frontmatter_mpdf.html
- lib/booktype/apps/themes/templates/themes/academic/frontmatter_screenpdf.html
- lib/booktype/apps/themes/templates/themes/style_mpdf.css
- lib/booktype/apps/themes/templates/themes/style_screenpdf.css
Using @page and pagebreak tags in combination is not reliable when the order of chapters and sections is arbitrary. So let's not use @page to switch between chapters and sections only to change header and footer visibility.
Please note that sections only start on an odd-numbered page for print PDF, as screen PDF is not left/right sided. This has the bonus of fewer blank pages to scroll through for screen PDF readers.
> BK-1385 Make page break method simpler

- lib/booktype/apps/themes/templates/themes/academic/body_mpdf.html
- lib/booktype/apps/themes/templates/themes/academic/body_screenpdf.html
- lib/booktype/apps/themes/templates/themes/custom/body_mpdf.html
- lib/booktype/apps/themes/templates/themes/custom/body_screenpdf.html
- lib/booktype/apps/themes/templates/themes/style_mpdf.css
- lib/booktype/apps/themes/templates/themes/style_screenpdf.css
We can set default header and footer names if the user has checked the boxes for these options, switching off the footers when required by the theme, for example on section pages.
The effect is that every page in the body of the book will get a page number, unless we explicitly switch it off using sethtmlpagefooter. 
Frontmatter is not affected because the named headers and footers are not yet defined at that point in the output file. Table of Contents pages have their own settings for showing page numbers or not.
> BK-1907 Set default header and footer names using @page rule

- lib/booktype/skeleton/themes/academic/mpdf.css
- lib/booktype/skeleton/themes/academic/screenpdf.css
- lib/booktype/skeleton/themes/custom/mpdf.css
- lib/booktype/skeleton/themes/custom/screenpdf.css
Without this change, you always get DejaVu Sans for the ToC. This can also increase PDF size, as a subset of DejaVu Sans gets embedded along with whatever font you actually wanted.
Also turn off the bold-by-default for all ToC lines, and italic-by-default for chapter lines in the Custom theme. It's kind of heavy.
> BK-1385 Table of Contents needs explicit font-family to avoid default

- lib/booktype/convert/mpdf/converter.py
- lib/booktype/convert/screenpdf/converter.py
- lib/booktype/skeleton/themes/academic/info.json
- scripts/booktype2mpdf.php
hi @danielhjames this might be of interest for you, now we can put mpdf configuration options in the theme info.json file. Something like this will work now:
```json
{
"version": "0.1",
"name": "Academic",
"output": {
"mpdf": {
"options": {
"useSubstitutions": true,
"mirrorMargins": false,
"h2bookmarks": {"H1": 0, "H2": 1, "H3": 2}
},
"frontmatter": "frontmatter_mpdf.html",
"endmatter": "endmatter_mpdf.html",
"body": "body_mpdf.html"
}
}
```
This will also work for screenpdf.
> BK-1928 Write extra mPDF configuration in the theme config file

- lib/booktype/skeleton/base_settings.py.original
Django only supports the nb code, see https://code.djangoproject.com/ticket/11068
> BK-1897 Correct language code for Norwegian Bokmål

- lib/booktype/apps/edit/static/edit/js/aloha/plugins/booktype/shortcuts/lib/shortcuts-plugin.js
Hi @aerkalov, I created this little PR because I found that select-all function does not work sometimes when having a lot of aloha blocks in the editor. Take a look of it please :)
> BK-1971 Select-all functionality does not work sometimes when multiple Aloha-blocks

- lib/booktype/skeleton/base_settings.py.original
lib/booktype/constants.py says:
PUBLISH_OPTIONS = ['mpdf', 'screenpdf', 'epub', 'mobi', 'xhtml']
> BK-1990 Get PUBLISH_OPTIONS base settings in sync with constants

- css/style.css
- index.html
Links on http://sourcefabric.github.io/Booktype/ are very out of date, and the colours do not match Booktype branding.
> BK-2001 Update GitHub developer page

- lib/booktype/apps/account/static/account/js/dashboard.js
- lib/booktype/apps/edit/static/edit/js/aloha/plugins/booktype/imagesimple/lib/imagesimple-plugin.js
- lib/booktype/apps/edit/static/edit/js/booktype/covers.js
- lib/booktype/apps/edit/static/edit/js/booktype/media.js
- lib/booktype/apps/edit/templates/edit/panel_covers.html
- lib/booktype/apps/edit/templates/edit/panel_media.html
Hi, Helmy.
This pr is kinda fix for all places (import book popup, image gallery in the editor, media and cover tabs) where we have ability upload image using dragndrop from file manager.
Right now, it is possible to move/drag/drop image/file to any area of the whole website, which is wrong. 
Also I found html elements with the same id on one page :) This was also fixed, but in requires template/js update for custom instances in case if they were overloaded.
> BK-2032 Some fileupload listeners attached to the whole document

- lib/booktype/apps/edit/channel.py
- lib/booktype/apps/edit/static/edit/js/booktype/editor.js
- lib/booktype/apps/edit/static/edit/js/booktype/toc.js
- lib/booktype/apps/edit/templates/edit/edit_config.html
We have good tools to control user permissions on the backend part, but we can't control them from JS app (editor). Now we check permissions by rendering or not rendering something in the templates, and it works just fine, but in some cases we need this logic on the JS level, for example in comments/component.jsx or other aloha plugins.
This user backbone model `var User = Backbone.Model.extend({....` is book oriented, it kinda repeats `BookSecurity(Security):` we have on python's level.
This pr provides next permission check:
`window.booktype.editor.data.currentUser.hasPerm('edit.add_comment')`
> BK-2034 Create ability to control permissions from JS app

- lib/booktype/utils/image_editor.py
We are changing image cache key from long: **ORIGINALFILENAME_edited_image_iw1497_ih936_tx252_ty157_fxFalse_fyFalse_rd0_con1.0_br1.0_bl0.0_sat1.0_op100_fw2003_fh1251.jpg** to fancy **2908d11e93c934dda348c6851c1347c2.jpg**
> BK-2060 Use md5 as key for edited image cache

- lib/booktype/constants.py
- lib/booktype/convert/epub/constants.py
- lib/booktype/convert/epub/converter.py
- lib/booktype/convert/epub/writerplugins/__init__.py
- lib/booktype/convert/epub/writerplugins/base_writerplugin.py
- lib/booktype/convert/epub/writerplugins/cleanup_tags_writerplugin.py
- lib/booktype/convert/epub/writerplugins/image_editor_writerplugin.py
Hi @eos87 , please check the PR.
I also moved writerplugins to the separate folder to have better file organisation in epub converter.
it can brake some instances, because import link to the WriterPlugin was changed from
`from .writerplugin import WriterPlugin` to `from .writerplugins import WriterPlugin`.
Just FYI, epub2 does not support `<u>` (underline) tag, epubcheck complains about it. 
With **this** plugin, we can also do replace, for example here configuration I have in **configuration.json** file for instance which has epub2 output:
```
"EPUB_NOT_ALLOWED_TAGS": [
{
"tag": "u",
"action": "replace",
"replacement": {
"tag": "span",
"attrs": [
[
"style",
"text-decoration: underline;"
]
]
}
}
]
```
it will find and convert `<u>TEXT</u>` to `<span style="text-decoration: …
> BK-2125 Create epub converter plugin to drop not allowed tags

- lib/booktype/apps/core/static/core/js/booki.js
- lib/booktype/apps/edit/static/edit/js/booktype/toc.js
Small commit just to make both buttons same colour on import docx dialog, both should be orange. This also allows the util function `confirm` to receive an extra param to specify a custom template for the `alert/dialog`
> BK-2215 DOCX import modal: append and overwrite same colour

- lib/booktype/skeleton/base_settings.py.original
- lib/booktype/urls.py
- requirements/_base.txt
Hi @eos87 ,
Check this PR. I've added https://github.com/fireantology/django-logtailer for our django admin. 
I put it into base settings and global urls, it means that this feature will be available for dev, stage and prod profiles. In general for production instances it's not very useful, because **www-data** doe's not have access to let's say apache/supervisor logs, but we still have access to the normal instance's logs folder.  It will be useful for stage instances as well. It will simplify our live at some point, so you don't need to do ssh just for reading logs. 
P.S. Currently it works similar to `tail -f`, it reads and shows updates. I checked library and it seems like it's possible to adjust it a little bit and have ability to read logs fully.
🍺 🍻 :man_technologist:
> BK-2263 Add ability to view log files from django admin

- lib/booktype/apps/account/static/account/js/dashboard.js
- lib/booktype/apps/core/static/core/js/booktype.js
Loading modal's content from a remote address was deprecated in bootstrap 3.3 so, this adds the ability to keep using modals loading their content from remote urls :)
> BK-2278 Modal dialogs with data-remote are not working

- lib/booktype/constants.py
- lib/booktype/convert/mpdf/converter.py
- simplified logic
- removed try/except, if error happens it means that we have wrong settings
- add ability to select custom crop margin using `crop_margin` export settings
- added `crop_margin` to the default export settings just to show that this option exists
> BK-2287 Add ability to provide custom crop margin size for mpdf converter

- lib/booktype/convert/pandoc/icml/converter.py
- lib/booktype/utils/image_editor.py
PR also contains one tiny update for image editor cache folder.
`# folder can be created by another process between os.path.exists and os.makedirs`
> BK-2294 Don't edit images for ICML output

- lib/booktype/skeleton/base_settings.py.original
PDF readers support subject and keyword metadata but we don't currently collect it. These values could then be used in templates.
> BK-2343 Collect additional metadata for PDF generation

- lib/booktype/apps/convert/plugin.py
- lib/booktype/apps/export/utils.py
This should solve the problem of having empty sections and the
section_count being incremented at the moment of saving settings. We
need to find a better way to create the unique keys instead of using
count which might be a bit unreliable under certain situations
> BK-2368 Sections settings exported incorrectly when empty sections exists

- lib/booktype/convert/pdf/constants.py
Adding these to constants so users needing these paper sizes don't have to choose 'Custom' paper sizes every time. These settings are optional in the template edit/panel_publish.html on the instance.
> BK-2260 Add paper sizes used by IDEA to constants

- lib/booktype/convert/epub/writerplugins/content_cleanup_plugin.py
Hi @eos87 ,
This pr is about how sweet lxml is :)
> ```python
> for elem in body.xpath("//*"):
> ```
I would expect lxml walk through objects inside body (I hope you also expected it), but it does not. It walks starting from the root (html element), which is wrong for us. Check a screenshot from my debugger: 
Here you can see what result gives `body.xpath("//*")` in our context.
```python
parent.remove(elem)
```
Here we see another lxml's feature. When we execute this command, lxml removes element, let's say an empty `<a>` and a content after it which belongs to parent. See a screenshot.
In this context elem is a reference to an empty `<a>` tag which is inside `<p>`, lxml removes an empty tag and rest of the content after it in context of parent's `<p>`. 
Please, test this pr with cases …
> BK-2435 ContentCleanUpPlugin sometimes removes valid content

- lib/booktype/apps/edit/templates/edit/panel_publish.html
- lib/booktype/apps/edit/views.py
Hi @eos87 ,we discussed this issue with @danielhjames and we decided to hide a custom page size and remove hardcoded page sizes from the templates. Now page sizes come from the PAGE_SIZE_DATA constant. This constant is overridable in setting file.
In the future we will move page sizes settings inside theme info file, so each theme will have their own settings. 
P.S. The same template changes were implemented for pdfreactor converter.
> BK-2260 Paper sizes should be an instance or theme setting, and margins optionally hidden

- lib/booktype/apps/edit/static/edit/css/edit.css
- lib/booktype/apps/edit/templates/edit/_section_settings_wizard.html
Also allow more space for translated words in the drop-down menu. Currently, the German translation does not fit well.
> BK-2470 Clarify labels for the section settings

- lib/booktype/apps/edit/channel.py
- lib/booktype/apps/edit/static/edit/js/booktype/editor.js
- lib/booktype/apps/edit/templates/edit/panel_media.html
Hi @eos87 ,
This is additional feature which makes image renaming for end user more comfortable. 
If image has been inserted into the book (chapters), user still can change image filename. System will change all filenames in entire book and also update another clients (myself=True) chapter's content with new value.
Cheers 🍺
> BK-2466 Rename all inserted images in chapters during image file renaming in media library

- requirements/prod.txt
Only fixes one of the deprecation warnings, but it works for me on a test instance.
> BK-2484 Fix for name change of psycopg2 package

- lib/booktype/apps/account/templates/account/register_form.html
- lib/booktype/locale/en/LC_MESSAGES/django.po
Remove example usernames which are not displayed anyway. Also some grammar fixes to strings.
> BK-2488 More helpful error message when username is too long

- lib/booktype/apps/export/utils.py
- lib/booktype/convert/epub/writer.py
Hi @danielhjames and @eos87 ,
This PR removes print's ISBN from epub files. 
MOBI output is a generic one and it's based on top of epub3.
> BK-1918 EPUB and MOBI output does not include correct ISBN from metadata settings

- requirements/_base.txt
Hi @ride90, this just locks out the requirement to avoid breaking changes issues. This is connected with #880
> BK-2493 Lock ebooklib requirement to latest github master stable commit

- lib/booktype/apps/edit/models.py
- lib/booktype/apps/edit/static/edit/js/booktype/toc.js
For new sections this will be set by default. For existent section, saving their settings is required
> BK-2391 Sets default `mark_section_as` setting to `mainmatter`

- lib/booktype/apps/edit/static/edit/js/aloha/plugins/booktype/simpletable/lib/simpletable-plugin.js
Fixes null `editable` on insert error.
This error occurred when the user tried to insert a table before clicking on the editor (i.e., immediately after loading a chapter in the editor).
> Fix Aloha `simpletable` plugin

- lib/booktypecontrol/forms.py
Use `STATIC_URL` instead of `BOOKTYPE_URL/static/`.
> Make static URLs consistent

- lib/booktype/skeleton/base_settings.py.original
This setting has been removed in [Django 1.5](https://docs.djangoproject.com/en/dev/releases/1.5/#django-contrib-admin) and is not used in the project.
> Remove ADMIN_MEDIA_PREFIX

- lib/booktype/apps/export/models.py
If export task is failed there is no file and therefore instance.filename is None and makes an error
> Fix remove export files if export has failed

- lib/booki/editor/views.py
- lib/booktype/apps/edit/views.py
Fixes using persian/arabic titles for meta data in cover manager.
> Fix using persian/arabic titles for book covers meta

- lib/booktype/apps/account/views.py
The selected value was ignored. Newly-created books were always visible to everyone.
The reason is that the value of `data.get('visible_to_everyone', None)` can be either `None` or `'on'`. So it should be compared with `'on'`, not `'off'`.
> Fix the "Visible to everyone" option
