lib/booktype/apps/core/static/core/css/bt20.css
lib/booktype/apps/core/static/core/js/booktype.js
lib/booktype/apps/core/templates/core/nav_bar.html
lib/booktype/apps/edit/static/edit/js/booktype/history.js
lib/booktype/apps/edit/templates/edit/chapter_history.html
lib/booktype/apps/edit/templates/edit/compare_screen.html
lib/booktype/apps/edit/urls.py
lib/booktype/apps/edit/views.py

In the Book History view, the chapter diff pop-up is 760px wide. This is too small for long chapters, because it means a lot of vertical scrolling is required, so now you can also open Chapter Diff in a new window

Open chapter diff in new tab instead of pop-up

---

lib/booktypecontrol/forms.py
lib/booktypecontrol/templates/booktypecontrol/_control_center_list_of_people.html

I've implemented this feature according to the ticket description.

BK-1314 Ability to define superuser in Control Center

---

lib/booktype/apps/edit/static/edit/js/booktype/settings.js

Dummy fix for "View Source" tab

BK-1356 Source View link is sometimes broken

---

lib/booktype/apps/edit/tasks.py

Added urllib module import and fix indent.

BK-1390 Added module import. Fix indent.

---

lib/booktype/apps/themes/static/themes/js/themes.js

Fixed line height from absolute to percent in #contentEditor

BK-1399 Fixed line height from absolute to percent in contentEditor

---

lib/booktypecontrol/forms.py

It was working before for me, so I just took the opportunity to make this file PEP8 compliant and added logging lines.

BK-1402 Invitation mail from control center not sent

---

lib/booktype/apps/edit/channel.py
lib/booktype/apps/edit/static/edit/js/booktype/toc.js
lib/booktype/apps/edit/templates/edit/panel_toc.html

BK-1437 Table of Contents reorder should check for the valid permissions

BK-1437 Table of Contents reorder should check for the valid permissions

---

lib/booktype/apps/edit/static/edit/js/booktype/toc.js

BK-1442 Chapter statuses in dropdown list not syncing (TOC)

BK-1442 Chapter statuses in dropdown list not syncing

---

lib/booktype/apps/edit/__init__.py
lib/booktype/apps/edit/channel.py
lib/booktype/apps/edit/templates/edit/panel_toc.html

BK-1436 Check permissions when checking chapter status change

BK-1436 Check permissions when checking chapter status change

---

lib/booktype/apps/edit/channel.py
lib/booktype/apps/edit/static/edit/js/booktype/toc.js

During researching nestedSortable jQuery plugin, I've found next info:
- All jQuery Sortable options, events and methods are available
I've changed callback event from "stop" to "update" (triggered when the user stopped sorting and the DOM position has changed)
http://api.jqueryui.com/sortable

BK-1466 ToC update is send even when nothing has changed

---

lib/booktype/skeleton/base_settings.py.original

There were several errors in this part of the file. Also I have put them back into alphabetical order.

BTPRO-618 Fix localization selector settings in original file

---

lib/booktype/apps/core/templates/core/footer.html

Simple update of the date and company name.

BK-1502 Update copyright notice in footer template

---

lib/booktype/apps/core/middleware.py
lib/booktype/apps/core/templates/core/nav_menu.html
lib/booktype/skeleton/base_settings.py.original

Tested with fresh install. You must update your base settings file, add "booktype.apps.core.middleware.SecurityMiddleware" in MIDDLEWARE_CLASSES tuple .

BK-1527 Load in context access to sidebar links

---

lib/booktype/apps/account/templates/account/dashboard.html
lib/booktype/apps/account/views.py
lib/booktype/apps/core/management/commands/update_default_roles.py
lib/booktype/locale/en/LC_MESSAGES/django.po
lib/booktype/skeleton/base_settings.py.original
lib/booktype/utils/security.py
lib/booktypecontrol/locale/en/LC_MESSAGES/django.po

I also updated the base strings for translation so Transifex can pull new strings now.

BK-1395 No Import for NON-Superuser in Firefox and Chrome

---

lib/booktype/apps/account/templates/account/dashboard.html
lib/booktype/apps/account/templates/account/other_user_box.html

BK-1543 Temporarily remove follow feature

---

lib/booktypecontrol/forms.py
lib/booktypecontrol/templates/booktypecontrol/new_person_email.html
lib/booktypecontrol/templates/booktypecontrol/password_changed_email.html
lib/booktypecontrol/views.py

new_person_email.html text was made translatable.

BK-1425 Re-send the login data to a person, when the password has been changed

---

lib/booktypecontrol/views.py

Fixes dummy error introduced by ugettext

BK-1547 django.utils.functional.__proxy__ object text in change password page

---

lib/booktype/apps/account/tasks.py

I checked beta instance and evething is working good. The emails are being delivered, its just that sometimes they got into spam box.
I just added an error logger

BK-1544 Check invitation mails are being delivered

---

lib/booktype/apps/core/middleware.py
lib/booktype/apps/core/static/core/js/booki.js
lib/booktype/apps/core/templatetags/booktype_tags.py
lib/booktype/apps/core/views.py
lib/booktype/apps/edit/__init__.py
lib/booktype/apps/edit/channel.py
lib/booktype/apps/edit/static/edit/js/booktype/edit.js
lib/booktype/apps/edit/templates/edit/_settings_form_chapter_status.html
lib/booktype/apps/edit/templates/edit/book_edit.html
lib/booktype/apps/edit/templates/edit/chapter_revision.html
lib/booktype/apps/edit/templates/edit/panel_aloha.html
lib/booktype/apps/edit/templates/edit/panel_covers.html
lib/booktype/apps/edit/templates/edit/panel_media.html
lib/booktype/apps/edit/templates/edit/panel_publish.html
lib/booktype/apps/edit/templates/edit/panel_toc.html
lib/booktype/apps/edit/templates/edit/toolbar_book.html
lib/booktype/apps/edit/views.py

I added multiple commits in one single PR because they're small isuees :)

Some Security checks 

---

lib/booktype/apps/core/static/core/js/booki.js
lib/booktype/apps/edit/static/edit/js/booktype/settings.js
lib/booktype/apps/edit/templates/edit/edit_config.html

This fixes the problem about the empty screen and redirect after saving settings

BK-1457 Empty screens in the Setting part

---

lib/booki/editor/models.py
lib/booktype/apps/edit/forms.py
lib/booktype/apps/edit/views.py
lib/booktype/apps/export/epub.py
lib/booktype/apps/export/utils.py
lib/booktype/apps/loadsave/management/commands/booksave.py
lib/booktype/apps/loadsave/views.py
lib/booktype/convert/epub/converter.py
lib/booktype/convert/mpdf/converter.py
lib/booktype/utils/misc.py

This adds 'author' field to book settings screen and also set the information stored in DB as metadata of epub file.

BK-1472 Add "Author" field to Metadata and set it to exported Epub file

---

lib/booktype/apps/core/templatetags/booktype_tags.py
lib/booktype/apps/edit/forms.py
lib/booktype/apps/edit/static/edit/js/booktype/history.js
lib/booktype/apps/edit/static/edit/js/booktype/settings.js
lib/booktype/apps/edit/templates/edit/_settings_form_license.html
lib/booktype/apps/edit/templates/edit/edit_config.html
lib/booktype/apps/edit/views.py
lib/booktype/apps/reader/templates/reader/book_full_view.html
lib/booktype/importer/epub/epubimporter.py

I'm sending two commits in one PR because they're small changes.

Removing unnecessary things and Full view working

---

lib/booki/editor/migrations/0003_update_books_toc.py
lib/booktype/apps/edit/tasks.py
lib/booktype/apps/export/utils.py

Note: just adding two commits into single PR because they're very tiny stories ;)

Blocker tickers: Failing tests and improve export_book function

---

lib/booktype/apps/edit/static/edit/js/aloha/plugins/booktype/endnotes/lib/endnotes-plugin.js

Also I've added in this pr: disable "insert endnote" link if cursor inside endnotes block or in the forbidden tag

BK-1629 Impossible insert endnote inside table.

---

lib/booki/editor/migrations/0003_update_books_toc.py

This I think should be a proper fix.

BK-1630 Tests are failing because of scheme migration

---

lib/booktype/apps/edit/tasks.py
lib/booktype/apps/export/admin.py
lib/booktype/apps/export/models.py

In addition I've registered BookExport model in django admin.

BK-1620 Publish page has excessive precision on timestamp

---

lib/booktype/skeleton/base_settings.py.original

New localization has already been pushed from Transifex.

BK-1659 Add English (United Kingdom) option to base settings

---

lib/booktype/apps/edit/static/edit/js/aloha/plugins/booktype/icejs/lib/icejs-plugin.js
lib/booktype/apps/edit/static/edit/js/booktype/edit.js

I'm just sending two commits in one single PR because both issues are pretty much related and are small fixes.

Some fixes for icejs issues

---

lib/booktype/apps/account/templates/account/dashboard.html
lib/booktype/apps/portal/templates/portal/all_groups.html
lib/booktype/apps/portal/templates/portal/group.html
lib/booktype/locale/en/LC_MESSAGES/django.po

Currently we have both 'Create new group' and 'Create New Group' but on a button the string is transformed to uppercase anyway.

BK-1361 Add some more tooltips and remove a duplicate string

---

lib/booktype/apps/edit/static/edit/js/aloha/plugins/booktype/findandreplace/lib/findandreplace-plugin.js
lib/booktype/apps/edit/static/edit/js/aloha/plugins/booktype/icejs/lib/icejs-plugin.js
lib/booktype/apps/edit/static/edit/js/booktype/edit.js

I didn't found a good way to handle this via PubSub or Aloha events so I needed to do it directly on the findAndReplace plugin. I hope it looks ok

BK-1661 Tracking changes does not register changes of Find And Replace plugin

---

lib/booktype/apps/core/templates/core/nav_bar.html
lib/booktype/apps/edit/templates/edit/toolbar_nav.html

Transifex changed their project URL format.

IN-1956 Update links to public Booktype projects on Transifex

---

lib/booktype/apps/edit/static/edit/js/booktype/edit.js
lib/booktype/apps/edit/static/edit/js/booktype/editor.js
lib/booktype/apps/edit/templates/edit/book_edit.html
lib/booktype/apps/edit/templates/edit/edit_strings.html
lib/booktype/locale/en/LC_MESSAGES/django.po
lib/booktypecontrol/locale/en/LC_MESSAGES/django.po
lib/booktypecontrol/templates/booktypecontrol/control_center_dashboard.html

BTPRO-685 Add tooltips for side tabs and fix string anomalies

---

lib/booktype/apps/core/static/core/css/bt20.css
lib/booktype/apps/portal/templates/portal/portal_add_book_modal.html

Fixes the issue on my test server, thanks to Darko!

BK-1667 Put Add Books button at the true end of the modal dialog

---

lib/booktype/apps/edit/static/edit/css/edit.css
lib/booktype/apps/themes/templates/themes/panel.html
lib/booktype/skeleton/themes/custom/panel.html

The panels in this tab needed some changes in order to match the appearance of other tabs.

BK-1682 Fix appearance of Choose Your Design and Custom Style panels

---

lib/booktype/apps/edit/static/edit/js/aloha/plugins/booktype/icejs/lib/icejs-plugin.js
lib/booktype/apps/edit/static/edit/js/aloha/plugins/common/format/lib/format-plugin.js
lib/booktype/apps/edit/static/edit/js/aloha/plugins/oer/toolbar/lib/toolbar-plugin.js
lib/booktype/apps/edit/static/edit/js/booktype/edit.js
lib/booktype/apps/edit/templates/edit/aloha_toolbar.html

This tracks changes for formatting actions (bold, italic and underline). I've created a separate ticket for link and image which I'm still working on. talk later

BK-1648 Ice.js feature does not fully track formatting events

---

lib/booki/editor/fixtures/documentation_licenses.json
lib/booki/editor/migrations/0002_load_initial_data.py
lib/booki/editor/south_migrations/0018_add_licenses_url.py

BTPRO-16 Add All Rights Reserved and AGPL v3 options

---

lib/booktype/apps/edit/static/edit/js/aloha/plugins/booktype/icejs/lib/icejs-plugin.js

Fixed only part with caret, when tracking changes is enabled and user deletes his own "green" text.

BK-1697 Hiting backspace moves caret to the end/start of current paragraph

---

lib/booktype/apps/core/templates/core/footer-demo.html
lib/booktype/apps/core/templates/core/footer.html
lib/booktype/apps/edit/templates/edit/panel_toc.html
lib/booktype/locale/en/LC_MESSAGES/django.po

Retain and rename original footer for demo site use

BK-1367 Remove demo information from default footer, fix message about sections for new books

---

lib/booktype/apps/edit/static/edit/js/aloha/plugins/booktype/icejs/lib/icejs-plugin.js

Fast hitting space moves caret somewhere in case of track changes is enabled and user edits his own "green" text

BK-1702 Fast hitting space moves caret somewhere in case of track changes is enabled

---

lib/booktype/apps/account/templates/account/dashboard.html
lib/booktype/apps/account/views.py
lib/booktype/apps/importer/views.py

I've also added access validation to the backend part. In case of book importing we should update js part for displaying "Permission denied" message, but this situation can be quite rare.

BK-1687 Privacy setting for book creation does not work

---

lib/booktype/apps/account/templates/account/forgot_password.html

We don't actually send the password in the reset email.

BK-1746 Revise password reset message to make it more accurate

---

lib/booktype/apps/edit/templates/edit/panel_publish.html
lib/booktype/locale/en/LC_MESSAGES/django.po

Links tested on my local instance.

BK-1757 Add helpful information to sidebar of Publish tab

---

lib/booktype/apps/edit/templates/edit/panel_publish.html
lib/booktype/locale/en/LC_MESSAGES/django.po

Julian asked for a change of wording.

BK-1757 Update help message to mention additional metadata

---

lib/booktype/apps/edit/forms.py

BK-1772 Add ability to use MultipleChoiceField in additional metadata of book

---

lib/booktypecontrol/templates/booktypecontrol/new_person_email.html

Using text adapted from the Omnibook instance.

BK-1776 Improve security of account creation notification

---

lib/booktype/apps/edit/templates/edit/panel_toc.html
lib/booktype/locale/en/LC_MESSAGES/django.po

Based on user feedback from Mozfest.

BK-1791 Clarify labels for chapter locking in the editor

---

lib/booktype/apps/account/templates/account/dashboard.html
lib/booktype/apps/portal/templates/portal/frontpage.html
lib/booktype/locale/en/LC_MESSAGES/django.po

Just a small improvement for a tooltip.

BK-1793 Improve book limit message so that deletion is optional!

---

lib/booktype/apps/edit/static/edit/js/aloha/plugins/booktype/linkbooktype/lib/linkbooktype-plugin.js
lib/booktype/convert/epub/converter.py

Two commits for two very small bug fixes. That's the only reason I opened a single PR for them.

BK-1813 and BK-1814

---

lib/booktype/apps/edit/static/edit/js/aloha/plugins/booktype/icejs/lib/icejs-plugin.js
lib/booktype/apps/edit/static/edit/js/icejs/ice.js

BK-1834 and BK-1835. Same PR because they're small commits

Fixes for icejs issues

---

lib/booktype/apps/edit/templates/edit/panel_covers.html

Might need to run "makemessages" since the text on the button was changed to "Save"

BK-1857 Cover editor. Edit button text to be "Save" when edit the cover

---

lib/booktype/apps/themes/templates/themes/custom/body_mpdf.html
lib/booktype/apps/themes/templates/themes/custom/body_screenpdf.html
lib/booktype/apps/themes/templates/themes/custom/frontmatter_mpdf.html
lib/booktype/apps/themes/templates/themes/custom/frontmatter_screenpdf.html
lib/booktype/apps/themes/templates/themes/style_mpdf.css
lib/booktype/apps/themes/templates/themes/style_screenpdf.css
lib/booktype/skeleton/themes/custom/mpdf.css
lib/booktype/skeleton/themes/custom/screenpdf.css

Similar to recent improvements for the Academic theme.

BTPRO-1081 Improvements to custom theme, including page breaking

---

lib/booktype/apps/edit/channel.py
lib/booktype/apps/edit/static/edit/js/booktype/publish.js
lib/booktype/apps/edit/tasks.py

Hey @aerkalov,
I'm not fully comfortable with this solution. I have another workaround in my mind but I would like to know your opinion before implementing it. Please let me know what you think or if you think this could break something.

BK-1932 Set the right extension for cover image in publishing

---

lib/booktype/apps/themes/templates/themes/panel.html
lib/booktype/skeleton/themes/academic/panel.html

Also correct original author for Academic theme

BK-1952 Use 'Themes' not 'Styles'

---

lib/booktype/apps/core/static/core/css/bt20.css
lib/booktype/apps/edit/static/edit/js/aloha/plugins/booktype/simpletable/lib/simpletable-plugin.js
lib/booktype/apps/edit/templates/edit/aloha_toolbar.html
lib/booktype/locale/en/LC_MESSAGES/django.po
lib/booktype/utils/misc.py

Hi @aerkalov, this PR is pretty simple, It only adds the ability to set a caption to the table that the user is inserting. You'll notice a bunch of changes but they mainly are indentation fixes and some variables definitions. Please let me know any concerns :)

BK-1973 Adding caption for tables on insert

---

lib/booktype/apps/edit/static/edit/js/aloha/plugins/booktype/simpletable/lib/simpletable-plugin.js

Hi @aerkalov,
this PR fix the tables markup into something like this:
```html
<div class="group_table">
<p class="caption_table">This is the table caption above the table.</p>
<table>
<tbody></tbody>
</table>
</div>
```
Please take a look of it and let me know any issues you find.

BK-1978 Standardize table's caption markup

---

lib/booktype/apps/edit/channel.py
lib/booktype/apps/edit/forms.py
lib/booktype/constants.py
lib/booktype/locale/en/LC_MESSAGES/django.po
lib/booktype/utils/book.py
lib/sputnik/utils.py
lib/sputnik/views.py

Hi @aerkalov, please take a look of the approach I have taken. I'm not fully sure about it but so far is the only way I could get this. Let's discuss this more in detail tomorrow if you think is not the best way :) Thanks!

BK-1993 Default status names should be defined in settings file and be translatable

---

lib/booktype/apps/edit/static/edit/js/aloha/plugins/booktype/comments/lib/comments-plugin.js
lib/booktype/apps/edit/templates/edit/edit_strings.html
lib/booktype/locale/en/LC_MESSAGES/django.po

Just so that it matches the other tooltips in the editor.

BK-1981 Consistent capitalisation for sidebar tooltip

---

INSTALL.md
README.md
lib/booktype/apps/core/templates/core/footer-demo.html
lib/booktype/apps/core/templates/core/nav_bar.html
lib/booktype/apps/edit/templates/edit/toolbar_user.html

Also update for Booktype 2.1 user manual where required.

BK-2046 Remove protocol from user manual links, use https for external links

---

lib/booktype/convert/mpdf/converter.py

Hey @olegpshenichniy,
I'm gonna merge this since it's urgent for mkt. The same way please have a look of it and let's discuss it in detail later.

BK-2055 Image editor fails in converter scripts (mpdf) when images is missing

---

lib/booki/locale/en/LC_MESSAGES/django.po
lib/booktype/apps/convert/plugin.py
lib/booktype/apps/edit/static/edit/css/edit.css
lib/booktype/apps/edit/static/edit/js/aloha/plugins/booktype/extraformat/lib/extraformat-plugin.js
lib/booktype/apps/edit/templates/edit/aloha_header.html
lib/booktype/apps/edit/templates/edit/aloha_toolbar.html
lib/booktype/apps/edit/templates/edit/edit_strings.html
lib/booktype/locale/en/LC_MESSAGES/django.po
lib/booktype/skeleton/themes/academic/epub.css
lib/booktype/skeleton/themes/academic/mpdf.css
lib/booktype/skeleton/themes/academic/screenpdf.css
lib/booktype/skeleton/themes/academic/static/editor.css
lib/booktype/skeleton/themes/bauhauscompact/epub.css
lib/booktype/skeleton/themes/bauhauscompact/mpdf.css
lib/booktype/skeleton/themes/bauhauscompact/screenpdf.css
lib/booktype/skeleton/themes/bauhauscompact/static/editor.css
lib/booktype/skeleton/themes/custom/epub.css
lib/booktype/skeleton/themes/custom/mpdf.css
lib/booktype/skeleton/themes/custom/screenpdf.css
lib/booktype/skeleton/themes/custom/static/editor.css
lib/booktype/skeleton/themes/novelclassiccompact/epub.css
lib/booktype/skeleton/themes/novelclassiccompact/mpdf.css
lib/booktype/skeleton/themes/novelclassiccompact/screenpdf.css
lib/booktype/skeleton/themes/novelclassiccompact/static/editor.css
lib/sputnik/__init__.py

Hey @olegpshenichniy, I create this PR just so you can take a look later of the diff :) Hear soon!

Blockquotes + authors tag [cite] 

---

lib/booktype/apps/edit/static/edit/js/aloha/plugins/booktype/comments/lib/components.jsx
lib/booktype/apps/edit/static/edit/js/aloha/plugins/booktype/extraformat/lib/extraformat-components.jsx
lib/booktype/apps/edit/static/edit/js/aloha/plugins/booktype/extraformat/lib/extraformat-plugin.js
lib/booktype/apps/edit/static/edit/js/react/components/modal.jsx
lib/booktype/apps/edit/templates/edit/aloha_toolbar.html
lib/booktype/apps/edit/templates/edit/book_edit.html
lib/booktype/apps/edit/templates/edit/edit_strings.html
lib/booktype/locale/en/LC_MESSAGES/django.po

Hey @olegpshenichniy, creating this and merging for you to check later. Julian needs this asap so I'm merging it.

BK-2067 Allow creating a cite just when user creates a quote

---

lib/booki/editor/models.py
lib/booki/locale/en/LC_MESSAGES/django.po

Update city field label to "City of publication" to match ONIX

BTPRO-1168 Add metadata field "Country of publication" to core

---

lib/booktype/skeleton/base_settings.py.original

BK-1897 Add Brazilian and Ukranian options to language menu

---

lib/booktype/apps/convert/plugin.py
lib/booktype/apps/edit/static/edit/css/edit.css
lib/booktype/apps/edit/static/edit/js/booktype/toc.js
lib/booktype/apps/edit/templates/edit/_section_settings_wizard.html
lib/booktype/apps/edit/templates/edit/panel_toc.html
lib/booktype/apps/themes/templates/themes/body_mpdf.html
lib/booktype/apps/themes/templates/themes/custom/body_mpdf.html
lib/booktype/apps/themes/templates/themes/custom/body_screenpdf.html
lib/booktype/convert/epub/converter.py
lib/booktype/convert/mpdf/converter.py
lib/booktype/convert/utils/epub.py
lib/booktype/importer/docx/docximporter.py
lib/booktype/locale/en/LC_MESSAGES/django.po
lib/booktype/skeleton/themes/academic/templates/body_mpdf.html
lib/booktype/skeleton/themes/academic/templates/body_screenpdf.html
lib/booktype/skeleton/themes/bauhauscompact/templates/body_mpdf.html
lib/booktype/skeleton/themes/bauhauscompact/templates/body_screenpdf.html
lib/booktype/skeleton/themes/novelclassiccompact/templates/body_mpdf.html
lib/booktype/skeleton/themes/novelclassiccompact/templates/body_screenpdf.html
lib/booktypecontrol/locale/en/LC_MESSAGES/django.po

hi @olegpshenichniy, take a look of this PR when you have some time. I still need to clarify one small thing tomorrow but I think you can start checking it already (if possible). Thanks
*UPDATE*
hey @olegpshenichniy, I think I completed the functionality for this ticket. Please have a look of it when you have some time. 
(to test this with an existent instance you should run `python manage.py reset_themes [theme names]` in order to get the latest updates of the themes

BK-2051 Section settings supporting structure

---

requirements/dev.txt

Hi @eos87 ,
Please, take a look on this update 🍺

BK-2099 Lock dev requirements

---

lib/booktype/convert/epub/converter.py
lib/booktype/convert/epub/writer.py

Hi @olegpshenichniy, please have a look of this as soon as you can. I need to deploy this to DNF asap.

BK-2103 Workaround nav file to be "compatible" with epub.js reader app

---

lib/booktype/apps/account/templates/account/signout.html
lib/booktype/apps/account/urls.py
lib/booktype/apps/account/views.py
lib/booktype/skeleton/base_settings.py.original
lib/booktype/urls.py

This removes the view we had that did not support either next support or LOGOUT_REDIRECT_URL settings.

BK-2104 Logout view should support `next` url param

---

lib/booki/messaging/templates/messaging/view_tag.html
lib/booktype/apps/reader/templates/reader/book_full_view.html

Hi @olegpshenichniy, will merge this also since is blocking me to deploy some changes on Avalanche instance. We can talk more in detail about this tomorrow ;)

BK-2110 Fixes broken offline compression

---

lib/booktype/apps/edit/static/edit/js/booktype/edit.js
lib/booktype/apps/edit/static/edit/js/booktype/editor.js

Hi @eos87 ,
Please, take a look on my comment in this ticket: BK-2074

BK-2074 Autosave function in editor (also comments)

---

lib/booktype/apps/importer/views.py
lib/booktype/apps/reader/views.py
lib/booktypecontrol/views.py

Hi @eos87 , please, take a look on this fix.

BK-2119 Remove RemovedInDjango110Warning warnings

---

lib/booktype/apps/edit/static/edit/js/aloha/plugins/booktype/comments/lib/components.jsx

Hey @olegpshenichniy, small change here. Just to show comments button/message on sidebar panel all the time.

BK-2062 Insert-comment-button disappearing on tab

---

lib/booki/editor/models.py
lib/booktype/api/__init__.py
lib/booktype/api/account/serializers.py
lib/booktype/api/account/views.py
lib/booktype/api/auth.py
lib/booktype/api/editor/serializers.py
lib/booktype/api/editor/views.py
lib/booktype/api/middleware.py
lib/booktype/api/security.py
lib/booktype/api/tokens.py
lib/booktype/api/urls.py
lib/booktype/api/views.py
lib/booktype/apps/account/views.py
lib/booktype/apps/core/middleware.py
lib/booktype/skeleton/base_settings.py.original
lib/booktype/urls.py
requirements/_base.txt

Hi @olegpshenichniy, please take a look of this and test it as soon as possible. I think we can release after integrating this :) (probably also after adding chapter history tab improvements)
Things to consider when testing this on already existent instances:
1. Install new requirements
2. Add to installed apps
```
'rest_framework',
'rest_framework.authtoken',
'rest_framework_swagger',
'booktype.api',
```
3. (optional) Add to middleware classes in case you want to use user_id and token authentication
```
'booktype.api.middleware.AuthMiddleware',
```
4. Add to settings
```
REST_FRAMEWORK = {
'DEFAULT_AUTHENTICATION_CLASSES': (
'rest_framework.authentication.SessionAuthentication',
'rest_framework.authentication.TokenAuthentication', # allows authenticating with token header
), …
```

BK-2084 Create REST API to communicate with other platforms

---

lib/booktype/api/editor/serializers.py
lib/booktype/apps/core/static/core/css/booki-new.css
lib/booktype/apps/importer/forms.py
lib/booktype/apps/importer/views.py
lib/booktype/constants.py
lib/booktype/importer/utils.py

Hi @olegpshenichniy, please check this as soon as you can. It's required by Avalanche people :)

BK-2153 Implement epub/docx importing through API

---

lib/booktype/apps/edit/static/edit/js/aloha/plugins/booktype/simpletable/lib/simpletable-plugin.js

Hi @olegpshenichniy, this is required by IDEA instance. Please check and merge as soon as you can. Thanks

BK-2158 Tables are not well recognized by aloha editor plugin

---

lib/booki/editor/models.py
lib/booktype/apps/portal/forms.py
lib/booktype/apps/portal/views.py
lib/booktype/utils/misc.py

@eos87 check this pr. 
I did some refactor and optimised book update query.

BK-2149 Remove errors during group creation/removing

---

lib/booktype/constants.py
lib/booktype/importer/docx/docximporter.py
lib/booktype/importer/docx/utils.py

Hi @olegpshenichniy, please check this as soon as you can please :) Btw it passed the test with your  killer docx file ;)

BK-2164 Allow infoboxes be imported from docx files

---

lib/booktype/apps/edit/templates/edit/aloha_toolbar.html
lib/booktype/locale/en/LC_MESSAGES/django.po

Tooltip says 'Change Heading' but this menu also changes paragraph styles.

BK-2172 More accurate tooltip for styles menu in editor

---

lib/booktype/apps/reader/templates/reader/book_info_page.html

Just commenting it out in HTML is good enough for now. We need it later.

Hide 'View Draft' the simple way.

---

lib/booktype/apps/edit/tasks.py
lib/booktypecontrol/forms.py
scripts/epub2docx.sh
scripts/epub2icml.sh

This PR also contains BK-2197.

BK-2200 Add suffix for icml/docx output file name

---

lib/booki/editor/models.py
lib/booki/locale/en/LC_MESSAGES/django.po
lib/booktype/apps/core/static/core/css/booki-new.css
lib/booktype/apps/edit/channel.py
lib/booktype/apps/edit/static/edit/js/booktype/toc.js
lib/booktype/apps/edit/templates/edit/panel_toc.html
lib/booktype/locale/en/LC_MESSAGES/django.po
lib/booktypecontrol/locale/en/LC_MESSAGES/django.po

Taking advantage and relocating icons below chapter’s title

BK-2204 Marker functionality and icon in TOC

---

lib/booktype/apps/edit/static/edit/js/aloha/plugins/booktype/simpletable/lib/simpletable-plugin.js

Hi @olegpshenichniy, please check this as soon as you can. For details about ticket see first part of `BK-2214` (not editable part) and also for testing you can use `TEST-demo.docx` attached to the ticket

BK-2219 SimpleTable plugin wrongly wraps whole content

---

lib/booktype/apps/edit/templates/edit/base.html

Adding path to favicon for editor templates

adding favicon to editor

---

lib/booktype/apps/edit/views.py
lib/booktype/skeleton/base_settings.py.original

Small change to complement rest of functionality ;)

BK-2223 Make ICC Profiles setting available in publish screen if any

---

lib/booki/utils/log.py
lib/sputnik/__init__.py

This makes sputnik method pep8 compatible and adds small fixes

Bk-2224 Sputnik improve addMessageToChannel method

---

lib/booktype/api/editor/serializers.py
lib/booktype/api/editor/views.py
lib/booktype/api/middleware.py
lib/booktype/apps/edit/channel.py
lib/booktype/skeleton/base_settings.py.original
lib/booktype/skeleton/dev_settings.py.original
lib/booktype/skeleton/prod_settings.py.original

I did not squash commits to make it easier for reviewing.
- correct logger for sputnik logs
- simplify logging settings and add separate logger handler for API things
- light API request/response logging middleware
- improve logging for all API endpoints

BK-2264 Improve logging

---

lib/booktype/apps/portal/templates/portal/frontpage.html
lib/booktype/apps/portal/views.py

Solving ticket https://dev.sourcefabric.org/browse/BK-2277
Related to ticket (partly solving) https://dev.sourcefabric.org/browse/BK-2244

Change home screen: remove activity stream and replace with users, change list length BK-2277

---

lib/booki/locale/en/LC_MESSAGES/django.po
lib/booktype/apps/account/templates/account/dashboard_create_book_modal.html
lib/booktype/apps/account/templates/account/dashboard_import_book_modal.html
lib/booktype/apps/reader/forms.py
lib/booktype/apps/reader/templates/reader/book_info_page.html
lib/booktype/locale/en/LC_MESSAGES/django.po
lib/booktypecontrol/forms.py
lib/booktypecontrol/locale/en/LC_MESSAGES/django.po

The current strings confuse the hidden book setting with the public viewing role. A book can be not hidden but still not public. Also there is no requirement that a book hidden initially will not be hidden later.

BK-2296 Clarify interface strings related to hidden books

---

lib/booktype/apps/edit/templates/edit/aloha_menu.html
locale/en/LC_MESSAGES/django.po

This only moves the menu to correct place according request of Julian.

BK-2276 Moving "Import DOCX File" entry to aloha "Insert" menu

---

lib/booktype/apps/account/__init__.py
lib/booktype/apps/account/forms.py
lib/booktype/apps/account/templates/account/dashboard.html
lib/booktype/apps/account/templates/account/dashboard_create_book_modal.html
lib/booktype/apps/account/templates/account/dashboard_import_book_modal.html
lib/booktype/apps/account/templates/account/form_signin.html
lib/booktype/apps/edit/templates/edit/edit_strings.html
lib/booktype/apps/edit/templates/edit/panel_settings.html
lib/booktype/apps/reader/__init__.py
lib/booktype/apps/reader/templates/reader/book_info_page.html
lib/booktype/locale/en/LC_MESSAGES/django.po

Also tidy up some formatting, for example <input> needs a closing slash.

BK-2347 Consolidate similar interface strings to save translation work

---

lib/booktype/apps/edit/static/edit/js/aloha/README.md
lib/booktype/apps/edit/static/edit/js/aloha/lib/aloha.js
lib/booktype/apps/edit/static/edit/js/aloha/package.json
lib/booktype/apps/edit/static/edit/js/aloha/plugins/booktype/bookundo/lib/bookundo-plugin.js
lib/booktype/apps/edit/static/edit/js/aloha/plugins/booktype/extraformat/lib/extraformat-plugin.js
lib/booktype/apps/edit/static/edit/js/aloha/plugins/booktype/imageeditor/lib/imageeditor-plugin.js
lib/booktype/apps/edit/static/edit/js/aloha/plugins/booktype/imagesimple/lib/imagesimple-plugin.js
lib/booktype/apps/edit/static/edit/js/aloha/plugins/booktype/simpletable/lib/simpletable-plugin.js

BK-2301 Upgrade Aloha editor to latest stable release

---

lib/booki/editor/fixtures/languages.json
lib/booktype/skeleton/base_settings.py.original

Thanks to Jujhar Singh for the interface translation work!

BK-2399 Add Punjabi (Gurmukhi script) option to language choices

---

lib/booktype/convert/image_editor_conversion.py
lib/booktype/skeleton/base_settings.py.original
lib/booktype/utils/image_editor.py

Hi @eos87 ,
This is a tricky one 🐝 
For testing it you need to install imagemagick, download and specify paths for color profiles in the settings (check base settings) (I will send icc profiles via email to you).
P.S. Don't use png images, png does not have support for cmyk color space.

BK-2404 Improve image processing in image editor

---

CHANGES.txt
INSTALL.md
docs/conf.py
docs/deployment/centos.rst
docs/deployment/macosx.rst
docs/development/profile.rst
docs/index.rst
lib/booktype/apps/core/templates/core/footer-demo.html
lib/booktype/apps/core/templates/core/nav_bar.html
lib/booktype/apps/edit/templates/edit/toolbar_user.html

Just routine updates for the 2.3 release.

BK-2417 Update links to manual and GitHub, bump copyright dates

---

lib/booktypecontrol/locale/en/LC_MESSAGES/django.po
lib/booktypecontrol/templates/booktypecontrol/_control_center_list_of_skeletons.html

Bonus: Make one less string to translate!

BK-2433 Make skeletons message less cryptic when there are none

---

lib/booktype/convert/epub/converter.py
lib/booktype/convert/image_editor_conversion.py
lib/booktype/convert/mpdf/converter.py
lib/booktype/convert/screenpdf/converter.py
lib/booktype/convert/xhtml/converter.py

Hi @eos87 , 
Please, check this PR 🍺

Converter class attribute which defines final images colour model

---

lib/booki/editor/models.py
lib/booktype/apps/edit/views.py

Hi @eos87 ,
This PR removes black (default) background for thumbnails where original file is PNG. Also I removed piece of weird and redundant code.

BK-2457 Preview for PNG images with transparency has black background

---

lib/booktype/apps/core/static/core/css/booki-new.css
lib/booktype/apps/edit/__init__.py
lib/booktype/apps/edit/channel.py
lib/booktype/apps/edit/static/edit/js/aloha/plugins/booktype/imagesimple/lib/imagesimple-plugin.js
lib/booktype/apps/edit/templates/edit/panel_aloha.html
lib/booktype/apps/edit/templates/edit/panel_media.html

Hi @eos87 ,
Check this pr. 
Now user can search images in media library by filename, width and height, and user has ability to rename file.
Here is some screenshots: 🍺

BK-2463 Improve media library in the editor

---

lib/booki/locale/en/LC_MESSAGES/django.po
lib/booktype/locale/en/LC_MESSAGES/django.po
lib/booktypecontrol/locale/en/LC_MESSAGES/django.po

A few new strings from recent features got left out.

BK-2470 Resync translation files with interface

---

lib/booktype/apps/core/static/core/css/booki-new.css
lib/booktype/apps/edit/static/edit/js/booktype/toc.js
lib/booktype/apps/edit/templates/edit/panel_toc.html

Hi @eos87 ,
Check it how it was:
and how this pr fixes it:

BK-2468 Better placement for info badges and improve appearance logic for different view modes

---

lib/booktype/apps/edit/templates/edit/book_edit.html
lib/booktype/locale/en/LC_MESSAGES/django.po

This button does not actually do what it says!

BK-2486 Change the button label and tooltip to match behaviour

---

lib/booktype/api/editor/views.py

Hi @ride90, This is really dummy but I found it was confusing for DNF dev. You can merge it with eyes closed xD

BK-2492 Small adjustments in doc string on editor api endpoints

---

lib/booki/messaging/templates/messaging/timeline.html
lib/booktype/apps/core/static/core/css/booki-new.css
lib/booktype/apps/portal/templates/portal/group_remove_book.html
lib/booktype/apps/reader/templates/reader/book_delete.html

Does not require a string update in this case.

BK-2434 Remove hard-coded italic text to avoid Asian interface breakage

---

requirements/_base.txt
requirements/legacy.txt

Also: Prevent downgrades after installing legacy libraries, then base

BK-2024 Ebooklib 0.17 is released

---

lib/booki/locale/en/LC_MESSAGES/django.po
lib/booki/messaging/templates/messaging/post.html
lib/booktype/apps/account/templates/account/dashboard.html
lib/booktype/apps/account/templates/account/dashboard_create_book_modal.html
lib/booktype/apps/account/templates/account/dashboard_group_template.html
lib/booktype/apps/edit/templates/edit/panel_settings.html
lib/booktype/apps/edit/templates/edit/settings/_roles.html
lib/booktype/apps/portal/templates/portal/all_groups.html
lib/booktype/apps/portal/templates/portal/books.html
lib/booktype/apps/portal/templates/portal/group.html
lib/booktype/apps/reader/templates/reader/book_info_page.html
lib/booktype/locale/en/LC_MESSAGES/django.po
lib/booktypecontrol/locale/en/LC_MESSAGES/django.po
lib/booktypecontrol/templates/booktypecontrol/_control_center_list_of_groups.html
lib/booktypecontrol/templates/booktypecontrol/_control_center_list_of_roles.html
lib/booktypecontrol/templates/booktypecontrol/_control_center_modal_person_info.html
lib/booktypecontrol/templates/booktypecontrol/control_center_dashboard.html

Also fixes BK-2441 and BK-2503. Thanks to Nicolas Dufour :-)

BK-2349 Interface string fixes from Flossmanuals FR, thanks Nicolas!

---

lib/booktype/apps/portal/templates/portal/books.html

Fixes error 500 at `/list-books`.

Fix list-books

---

lib/booktype/apps/core/widgets.py
tests/func_settings.py
tests/selenium_settings.py
tests/settings.py

Fix regression in the tests (see [BK-2499](https://dev.sourcefabric.org/browse/BK-2499) for details).

Django 1.9 regression fix

---

lib/booktype/convert/epub/constants.py
lib/booktype/convert/epub/converter.py
lib/booktype/convert/epub/writerplugins/base_writerplugin.py

Fixes direction for RTL books.

Add direction to epub books

---

lib/booktype/apps/export/models.py

**Previous behavior:** When an ExportFile instance is deleted (e.g. when the user removes an export), the exported files will not be deleted (they remain in `BOOKTYPE_ROOT/data/tmp`).
**New behavior:** The exported files (and related directories) are deleted on instance deletion.

Delete export files on instance deletion
